services:
  redis:
    image: redis:latest
    container_name: redis-fitai
    env_file:
      - ./backend/.env
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run start:dev
    container_name: FIT-AI-backend
    ports:
      - "4000:4000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: FIT-AI-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - backend
