services:
  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - ./backend/.env
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run start:dev
    container_name: nest-backend
    ports:
      - "4000:4000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
